# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Float Necessary Windows
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:title ^(Picture in picture)$
windowrule = float on, match:title ^(Save File)$
windowrule = float on, match:title ^(Open File)$
windowrule = float on, match:class LibreWolf, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)
windowrule = float on, match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.kde.polkit-kde-authentication-agent-1|qt-sudo)
windowrule = float on, match:class CachyOSHello
windowrule = float on, match:class zenity
windowrule = float on, match:title ^(Steam - Self Updater)$
#windowrule = float on, match:title ^(Steam)$
windowrule = float on, match:class steam, match:title ^(Steam Settings)$
windowrule = float on, match:class steam, match:title ^(Friends List)$

# Workspace assignments
#windowrule = workspace 4 silent, match:class steam
windowrule = workspace 2 silent, match:class discord

# Picture-in-Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = size 960 540, match:title ^(Picture-in-Picture)$
windowrule = move 25% 25%, match:title ^(Picture-in-Picture)$

# Media floats
windowrule = float on, match:class ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = size 960 540, match:class ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = move 25% 25%, match:class ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = pin on, match:class danmufloat
windowrule = rounding 5, match:class ^(danmufloat|termfloat)$
