color0 #101510
color1 #ffb4ab
color2 #9ad4a1
color3 #a1ced8
color4 #b5f1bc
color5 #d3e8d2
color6 #b7ccb6
color7 #dfe4dc
color8 #363a35
color9 #ffb4ab
color10 #9ad4a1
color11 #a1ced8
color12 #b5f1bc
color13 #d3e8d2
color14 #b7ccb6
color15 #dfe4dc
background #101510
selection_foreground #9ad4a1
cursor #dfe4dc
cursor_text_color #414941
foreground #dfe4dc
selection_background #003916
active_border_color #9ad4a1
inactive_border_color #b7ccb6

active_tab_foreground   #003916
active_tab_background   #9ad4a1
inactive_tab_foreground #c1c9be
inactive_tab_background #101510
cursor_trail_color      #c1c9be
